{
 "title": "All data",
 "time": { "from": "2025-03-20T04:00:00.000Z", "to": "2025-04-11T03:59:59.000Z" },
 "panels": [
  {
   "title": "Total Tcp bytes ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", SUM(tcp_bytes_sent), SUM(tcp_bytes_received) FROM main.device_info GROUP BY date;"
    }
   ]
  },
  {
   "title": "Total Udp bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", SUM(udp_bytes_sent), SUM(udp_bytes_received) FROM main.device_info GROUP BY date; "
    }
   ]
  },
  {
   "title": "Total Icmp bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", SUM(icmp_bytes_received), SUM(icmp_bytes_sent) FROM main.device_info GROUP BY date; "
    }
   ]
  },
  {
   "title": "Total DNS queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", SUM(dns_queries), SUM(distinct_dns_queries) FROM main.device_info GROUP BY date; "
    }
   ]
  }
 ]
}