{
 "title": "DNS Data Visualization India",
 "time": { "from": "2025-01-07T01:00:00.000Z", "to": "2025-04-19T00:00:00.000Z" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "ip_address_filter",
    "label": "Filter by IP address",
    "query": "SELECT DISTINCT  ip_address FROM main.device_status order by ip_address asc;"
   }
  ]
 },
 "panels": [
  {
   "title": "general ip address filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '${ip_address_filter:single}' "
    }
   ]
  },
  {
   "title": "PixStar_FotoConnect - 192.168.2.2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.2'"
    }
   ]
  },
  {
   "title": "Google_NestProtect - 192.168.2.3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.3' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Samsung_WisenetSmartCam_A1 - 192.168.2.4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.4'"
    }
   ]
  },
  {
   "title": "Link_TapoHomesecurityCamera - 192.168.2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.5'"
    }
   ]
  },
  {
   "title": "Dlink_Omna180CamHD - 192.168.2.6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.6'"
    }
   ]
  },
  {
   "title": "Sengled_SmartBulbStarterKit - 192.168.2.8",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.8'"
    }
   ]
  },
  {
   "title": "Amazon_EchoDot3rdGeneration - 192.168.2.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.9' "
    }
   ]
  },
  {
   "title": "Amazon_EchoDot - 192.168.2.10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.10'"
    }
   ]
  },
  {
   "title": "Amazon_Echo - 192.168.2.11",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.11' "
    }
   ]
  },
  {
   "title": "Withings_Body+SmartScale - 192.168.2.12",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.12' "
    }
   ]
  },
  {
   "title": "Wansview_WirelessCloudcamera - 192.168.2.15",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.15' "
    }
   ]
  },
  {
   "title": "SmartAtoms_LaMetricTime - 192.168.2.16",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.16' "
    }
   ]
  },
  {
   "title": "Netatmo_SmartHomeWeatherStation - 192.168.2.17",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.17' "
    }
   ]
  },
  {
   "title": "HP_OfficeJetPro6978 - 192.168.2.18",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.18' "
    }
   ]
  },
  {
   "title": "TP-Link_TapoMiniSmartWifiSocket1 - 192.168.2.19",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.19' "
    }
   ]
  },
  {
   "title": "TP-Link_TapoMiniSmartWifiSocket2  - 192.168.2.20",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.20' "
    }
   ]
  },
  {
   "title": "TP-Link_KasaSmartWifiPlugMini1 - 192.168.2.21",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.21' "
    }
   ]
  },
  {
   "title": "TP-Link_KasaSmartWifiPlugMini2  - 192.168.2.22",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.22'"
    }
   ]
  },
  {
   "title": "Lifx_SmarterLights - 192.168.2.23",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.23'"
    }
   ]
  },
  {
   "title": "TP-Link_KasaSmartWiFiLightBulbMulticolor - 192.168.2.24",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 149 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.24'"
    }
   ]
  },
  {
   "title": "Philips_HueBridge - 192.168.2.25",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 156 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.25'"
    }
   ]
  },
  {
   "title": "D-Link_FullHDPan&TiltProHDWifiCamera - 192.168.2.26",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 163 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.26'"
    }
   ]
  },
  {
   "title": "Meross_SmartWiFiGarageDoorOpener - 192.168.2.30",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 170 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.30'"
    }
   ]
  },
  {
   "title": "Yi_1080pHomeCameraAIPlus - 192.168.2.31",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 177 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.31'"
    }
   ]
  },
  {
   "title": "iRobot_RoombaRobotVaccum - 192.168.2.32",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 184 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.32'"
    }
   ]
  },
  {
   "title": "Reolink_RLC520Camera1 - 192.168.2.33",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 191 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.33' "
    }
   ]
  },
  {
   "title": "Reolink_RLC520Camera2 - 192.168.2.34",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 198 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.34'"
    }
   ]
  },
  {
   "title": "Amcrest_SecurityTurretCamera - 192.168.2.35",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 205 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.35' "
    }
   ]
  },
  {
   "title": "Wemo_WiFiSmartLightSwitch - 192.168.2.37",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 212 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.37' "
    }
   ]
  },
  {
   "title": "Ecobee_Switch+ - 192.168.2.38",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 219 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.38' "
    }
   ]
  },
  {
   "title": "Blink Sync Module 2 - 192.168.2.40",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 226 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.40' "
    }
   ]
  },
  {
   "title": "Blink Mini indoor Plug-In HD smart security Camera - 192.168.2.41",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 233 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.41' "
    }
   ]
  },
  {
   "title": "Google nest Mini - 192.168.2.42",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 240 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.42' "
    }
   ]
  },
  {
   "title": "Insignia_FireTV - 192.168.2.43",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 247 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.43'"
    }
   ]
  },
  {
   "title": "Xiaomi_360HomeSecurityCamera2k - 192.168.2.44",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 254 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.44'"
    }
   ]
  },
  {
   "title": "TP-Link_KasaSmartLightStrip - 192.168.2.47",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 261 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.47'"
    }
   ]
  },
  {
   "title": "Ring_Doorbell4 - 192.168.2.48",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 268 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.48' "
    }
   ]
  },
  {
   "title": "Ecobee_3liteSmartThermostat - 192.168.2.49",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 275 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.49' "
    }
   ]
  },
  {
   "title": "Google_NestThermostat - 192.168.2.50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 282 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.50'"
    }
   ]
  },
  {
   "title": "August Wi-fi Smart Lock - 192.168.2.245",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 289 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", dns_queries, distinct_dns_queries FROM main.device_info WHERE ip_address = '192.168.2.245' "
    }
   ]
  }
 ]
}