{
 "title": "Tcp Data Visualization India",
 "time": { "from": "2025-03-11T00:00:00.000Z", "to": "2025-04-09T00:00:00.000Z" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "ip_address_filter",
    "label": "Filter by IP address",
    "query": "SELECT DISTINCT  ip_address FROM main.device_status order by ip_address asc;"
   }
  ]
 },
 "panels": [
  {
   "title": "general Tcp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '${ip_address_filter:single}';  "
    }
   ]
  },
  {
   "title": "PixStar_FotoConnect - 192.168.2.2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.2'"
    },
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.2' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Google_NestProtect - 192.168.2.3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.3'"
    }
   ]
  },
  {
   "title": "Samsung_WisenetSmartCam_A1 - 192.168.2.4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.4' "
    }
   ]
  },
  {
   "title": "Link_TapoHomesecurityCamera - 192.168.2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.5'  "
    }
   ]
  },
  {
   "title": "Dlink_Omna180CamHD - 192.168.2.6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.6'  "
    }
   ]
  },
  {
   "title": "Sengled_SmartBulbStarterKit - 192.168.2.8",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.8' "
    }
   ]
  },
  {
   "title": "Amazon_EchoDot3rdGeneration - 192.168.2.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.9'  "
    }
   ]
  },
  {
   "title": "Amazon_EchoDot - 192.168.2.10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.10'  "
    }
   ]
  },
  {
   "title": "Amazon_Echo - 192.168.2.11",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.11'  "
    }
   ]
  },
  {
   "title": "Withings_Body+SmartScale - 192.168.2.12",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.12'  "
    }
   ]
  },
  {
   "title": "Wansview_WirelessCloudcamera - 192.168.2.15",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.15' "
    }
   ]
  },
  {
   "title": "SmartAtoms_LaMetricTime - 192.168.2.16",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.16'"
    }
   ]
  },
  {
   "title": "Netatmo_SmartHomeWeatherStation - 192.168.2.17",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.17' "
    }
   ]
  },
  {
   "title": "HP_OfficeJetPro6978 - 192.168.2.18",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.18'  "
    }
   ]
  },
  {
   "title": "TP-Link_TapoMiniSmartWifiSocket1 - 192.168.2.19",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.19' "
    }
   ]
  },
  {
   "title": "TP-Link_TapoMiniSmartWifiSocket2  - 192.168.2.20",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.20' "
    }
   ]
  },
  {
   "title": "TP-Link_KasaSmartWifiPlugMini1 - 192.168.2.21",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.21' "
    }
   ]
  },
  {
   "title": "TP-Link_KasaSmartWifiPlugMini2  - 192.168.2.22",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.22' "
    }
   ]
  },
  {
   "title": "Lifx_SmarterLights - 192.168.2.23",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.23'  "
    }
   ]
  },
  {
   "title": "TP-Link_KasaSmartWiFiLightBulbMulticolor - 192.168.2.24",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 148 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.24'  "
    }
   ]
  },
  {
   "title": "Philips_HueBridge - 192.168.2.25",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 155 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.25'  "
    }
   ]
  },
  {
   "title": "D-Link_FullHDPan&TiltProHDWifiCamera - 192.168.2.26",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.26'  "
    }
   ]
  },
  {
   "title": "Meross_SmartWiFiGarageDoorOpener - 192.168.2.30",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 169 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.30'  "
    }
   ]
  },
  {
   "title": "Yi_1080pHomeCameraAIPlus - 192.168.2.31",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 176 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.31'  "
    }
   ]
  },
  {
   "title": "iRobot_RoombaRobotVaccum - 192.168.2.32",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 183 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.32' "
    }
   ]
  },
  {
   "title": "Reolink_RLC520Camera1 - 192.168.2.33",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 190 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.33'  "
    }
   ]
  },
  {
   "title": "Reolink_RLC520Camera2 - 192.168.2.34",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 197 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.34' "
    }
   ]
  },
  {
   "title": "Amcrest_SecurityTurretCamera - 192.168.2.35",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 204 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.35' "
    }
   ]
  },
  {
   "title": "Wemo_WiFiSmartLightSwitch - 192.168.2.37",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 211 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.37' "
    }
   ]
  },
  {
   "title": "Ecobee_Switch+ - 192.168.2.38",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 218 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.38'  "
    }
   ]
  },
  {
   "title": "Blink Sync Module 2 - 192.168.2.40",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 225 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.40' "
    }
   ]
  },
  {
   "title": "Blink Mini indoor Plug-In HD smart security Camera - 192.168.2.41",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 232 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.41' "
    }
   ]
  },
  {
   "title": "Google nest Mini - 192.168.2.42",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 239 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.42' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Insignia_FireTV - 192.168.2.43",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 246 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.43' "
    }
   ]
  },
  {
   "title": "Xiaomi_360HomeSecurityCamera2k - 192.168.2.44",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 253 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.44'  "
    }
   ]
  },
  {
   "title": "TP-Link_KasaSmartLightStrip - 192.168.2.47",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 260 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.47' "
    }
   ]
  },
  {
   "title": "Ring_Doorbell4 - 192.168.2.48",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 267 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.48' "
    }
   ]
  },
  {
   "title": "Ecobee_3liteSmartThermostat - 192.168.2.49",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 274 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.49'  "
    }
   ]
  },
  {
   "title": "Google_NestThermostat - 192.168.2.50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 281 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.50'  "
    }
   ]
  },
  {
   "title": "August Wi-fi Smart Lock - 192.168.2.245",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 288 },
   "targets": [
    {
     "dataset": "main",
     "rawSql": "SELECT date AS \"time\", tcp_bytes_sent, tcp_bytes_received FROM main.device_info WHERE ip_address = '192.168.2.245' LIMIT 50 "
    }
   ]
  }
 ]
}